### ISSUE TITLE
Price History X-Axis Is Wrong & Labels Hard To Read

### ISSUE THREAD

**Issue by crahen** [owlracle/webserver#1]
The gas tracker graph isn't super useful because your x-axis is all screwed up in terms of both scale and labels.

The 1-day button shows most of a month
The 4-hr button shows most of a week
The 2-hr button shows most of 2 days
The 1-hr button shows most of 1 day
The 30-min buttons shows roughly 1/2 of a day
The 10-min button shows about 30-min

I attached a screen shot of the 4-hr example, you can see the x-axis is spanning days.

It's also hard to make any sense of the labels since they switch between day of month and hour:second with no labels. Pick 1-unit for your axis

![sample](https://user-images.githubusercontent.com/861103/155546796-57e8c51d-cfab-4432-9e20-92bf4b13c1b8.png)

**Comment by werlang** [comment]
Hello. The history endpoint got changed yesterday. It is now ~50x faster than before. As our database got bigger, optimization was due.

So I'd like you to kindly check our chart again, and see if you get any errors on it, and please report if you do.

It is also worth noting that the timeframe buttons are relative to that candle size. So a 4h candle means every point in the chart is an aggregate of 4 hours worth of samples.
So the timeframe buttons are not about the visuals of the chart, or how much data it shows on a single screen, as the scale can be increased or reduced using mouse scrolling. The timeframe buttons control how much time is covered on EACH point in the x-axis.
